<?php
// Include the main TCPDF library (search for installation path).
require_once 'vendor/autoload.php';
require_once 'db.php';

// Extend TCPDF with custom functions
class MYPDF extends TCPDF {

    // Load data from database
    public function LoadDataFromDatabase($conn) {
        $data = array();
        $sql = "SELECT id, transaction_date, cash, card, total, expenditure, comment FROM daily_transactions";
        $result = $conn->query($sql);
        
        if ($result->num_rows > 0 && $result->num_rows <=31) {
            while($row = $result->fetch_assoc()) {
                $data[] = $row;
            }
        }
        return $data;
    }

    // Colored table
    public function ColoredTable($header, $data) {
        // Colors, line width and bold font
        $this->SetFillColor(0, 0, 128);
        $this->SetTextColor(255);
        $this->SetDrawColor(128, 0, 0);
        $this->SetLineWidth(0.3);
        $this->SetFont('', 'B');
        // Header
        $w = array(10, 30, 20, 20, 20, 30, 60);
        $num_headers = count($header);
        for($i = 0; $i < $num_headers; ++$i) {
            $this->Cell($w[$i], 7, $header[$i], 1, 0, 'C', 1);
        }
        $this->Ln();
        // Color and font restoration
        $this->SetFillColor(235, 255, 255);
        $this->SetTextColor(0);
        $this->SetFont('');
        // Data
        $fill = 0;
        $total_cash = 0;
        $total_card = 0;
        $total_total = 0;
        $total_expenditure = 0;

        foreach($data as $row) {
            $this->Cell($w[0], 6, $row['id'], 'LR', 0, 'L', $fill);
            $this->Cell($w[1], 6, $row['transaction_date'], 'LR', 0, 'L', $fill);
            $this->Cell($w[2], 6, $row['cash'], 'LR', 0, 'R', $fill);
            $this->Cell($w[3], 6, $row['card'], 'LR', 0, 'R', $fill);
            $this->Cell($w[4], 6, $row['total'], 'LR', 0, 'R', $fill);
            $this->Cell($w[5], 6, $row['expenditure'], 'LR', 0, 'R', $fill);
            $this->Cell($w[6], 6, $row['comment'], 'LR', 0, 'L', $fill);
            $this->Ln();
            $fill=!$fill;

            // Calculate totals
            $total_cash += $row['cash'];
            $total_card += $row['card'];
            $total_total += $row['total'];
            $total_expenditure += $row['expenditure'];
        }
        $this->Cell(array_sum($w), 0, '', 'T');

        // Print totals summary
        $this->Ln(5); // Add some space
        $this->SetFont('helvetica', 'B', 14);
        $this->Cell(0, 10, "Totals Summary", 0, 1, 'C');
        $this->SetFont('helvetica', 'B', 12);
        $this->Cell(0, 10, "Total Cash: " . $total_cash, 0, 1, 'L');
        $this->Cell(0, 10, "Total Card: " . $total_card, 0, 1, 'L');
        $this->Cell(0, 10, "Total Total: " . $total_total, 0, 1, 'L');
        $this->Cell(0, 10, "Total Expenditure: " . $total_expenditure, 0, 1, 'L');
    }
}

// Database connection
$hostname = 'localhost';
$username = 'root';
$password = '';
$database_name = 'seat_cafe';

// Create connection
$conn = new mysqli($hostname, $username, $password, $database_name);

if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

// Create new PDF document
$pdf = new MYPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// Set document information
$pdf->SetAuthor('Nazri Tamale');
$pdf->SetTitle('Seat Cafe Report');
$pdf->SetSubject('Transaction Report');
$pdf->SetKeywords('SEAT CAFE, PDF');

// Set default header data
$pdf->SetHeaderData('', 0, 'SEAT CAFE REPORT', 'Generated by Nazri Tamale');

// Set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// Set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// Set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// Set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// Set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// Set some language-dependent strings (optional)
if (@file_exists(dirname(__FILE__).'/lang/eng.php')) {
    require_once(dirname(__FILE__).'/lang/eng.php');
    $pdf->setLanguageArray($l);
}

// Set font
$pdf->SetFont('helvetica', '', 12);

// Add a page
$pdf->AddPage();

// Column titles
$header = array('ID', 'Date', 'Cash', 'Card', 'Total', 'Expenditure', 'Comment');

// Data loading
$data = $pdf->LoadDataFromDatabase($conn);

// Print colored table
$pdf->ColoredTable($header, $data);

// Get the current date in a desired format
$currentDate = date('Ymd_His'); // Example format: YYYYMMDD_HHmmss

// Output the PDF with the current date in the file name
$pdf->Output($currentDate . 'Monthly_report.pdf', 'I');

$conn->close();
?>
